#!/bin/bash -l
## use tecplot batch mode to generate 3D contour plots
## the layout files /.lay/ and layer files /.dat/ are generated by Xuehang using tec360
## written by Xuehang Song 03/01/2018
## revised by Xuehang Song 04/13/2018


# case_name="s7_4b"
# reazs=base
# ireaz=$reazs
# data_dir="/pic/scratch/song884/fy2018/"$case_name"/"$ireaz"/tec_data/"
# fig_dir="/people/song884/dust/fy2018/"$case_name"/figures/"$ireaz"/"
# scripts_dir="/people/song884/dust/fy2018/s7_1a/scripts/"

cp $scripts_dir*".lay" $data_dir
cp $scripts_dir*".mcr" $data_dir
cp $scripts_dir"layer.dat" $data_dir

if [ ! -d $fig_dir$icase/ ] ; then
    mkdir $fig_dir$icase/
fi

layouts=(
    $data_dir"s7_i129_slice_with_layer.lay"    
    $data_dir"s7_satu_slice_with_layer.lay"
)
layer=$data_dir"layer.dat"

cd $data_dir
for ilayout in ${layouts[@]}
do
    echo $ilayout
    fig_prefix=$(echo $ilayout |rev| cut -d "/" -f 1|rev|cut -d "." -f 1)
    for iplt in $(ls -rt *plt)
    do
	echo $iplt 
	itime=$(echo $iplt | cut -d "." -f 1-2)
	ifig=$fig_dir$fig_prefix"_"$itime.jpg
	iplt=$data_dir$iplt

	solutiontime="  SOLUTIONTIME = "$itime
	sed -i "/$!GLOBALTIME/!b;n;c\ $solutiontime" $ilayout

	mcr_layout="\$!OPENLAYOUT = \"$ilayout\""
	sed -i "/$!OPENLAYOUT/c\\$mcr_layout" \
	    $data_dir"tecplot.mcr"

	mcr_data="ALTDATALOADINSTRUCTIONS = '\"$iplt\" \"$layer\"'"
	echo $mcr_data
	sed -i "/ALTDATALOADINSTRUCTIONS/c\\$mcr_data" \
	    $data_dir"tecplot.mcr"

	mcr_fig="\$!EXPORTSETUP EXPORTFNAME = \"$ifig\""
	echo $mcr_fig
	sed -i "/EXPORTFNAME/c\\$mcr_fig" \
	    $data_dir"tecplot.mcr"
	
	tec360 -b -p $data_dir"tecplot.mcr"
    done
done
