#This program scales homogeneous porosity and permeability values using standard normal scores generated by GSLIB
#setwd('/Users/rupr404/Desktop/GSLIB_bin')
setwd("/people/song884/dust/fy18/NQAP/")
options(stringsAsFactors = FALSE)
rm(list=ls(all=TRUE))
#set model
  df<-read.csv('nn.csv', skip=2)
  #
  #back transform from std normal scores to normal porosity values
  # Std_dev and porosity taken from Truex et al., (2017) report (PNNL-24709, Rev. 2; RPT-DVZ-AFRI-030, Rev. 2).
  stddev_n<-0.1
  #set n-avg to 1 minus the average
  n_avg<- (1.-0.35)
  dfn<-df*stddev_n+n_avg
  dfn<-1.-dfn
  dfn<-abs(dfn)
  tdfn<-t(dfn)
  #dimensions of zone
  dim(tdfn)=c(1100,501*8)
  write.table(dfn,file="n_CCUZ.txt", row.names = F, col.names = F)
  #
  #back transform from std normal scores to log normal perm values
  # Std_dev and permeability taken from Truex et al., (2017) report (PNNL-24709, Rev. 2; RPT-DVZ-AFRI-030, Rev. 2).
  stddev_logk<- 1.
  #must be positive for this calculation and converted to negative after. 
  logk_avg<- 14.1789968165
  dflogk<-df*stddev_logk+logk_avg
  dflogk<-abs(dflogk)*-1.
  tdflogk<-t(dflogk)
  dim(tdflogk)=c(1100,501*8)
  write.table(dflogk,file="logk_CCUZ.txt", row.names = F, col.names = F)
  #
