#!/bin/bash  -l
#SBATCH -A dvz
#SBATCH -t 7-00:00:00
#SBATCH -p shared
#SBATCH -n 1
#SBATCH -J tecplot
#SBATCH --mail-type=ALL
#SBATCH --mail-user=xuehang.song@pnnl.gov


#-------------------------------
# use tecplot batch mode to generate 3D contour plots
# the layout files /.lay/ and layer files /.dat/ are
# generated by Xuehang using tec360

## written by Xuehang Song 03/01/2018
## revised by Xuehang Song 06/05/2018

module remove tecplot*
module load tecplot/2015r2
ulimit -s unlimited

cp $scripts_dir*"lay" $simu_dir$icase/
cp $scripts_dir"tecplot.mcr" $simu_dir$icase/

cd $simu_dir$icase"/tec_data"
if [ ! -d $figures_dir$icase/ ] ; then
    mkdir $figures_dir$icase/
fi

for ilayout in  $layouts
do
    echo $ilayout
    ilayout_dir=$simu_dir$icase/$ilayout
    
    fig_prefix=$(echo $ilayout_dir |rev| cut -d "/" -f 1|rev|cut -d "." -f 1)
    for iplt in $(ls -rt *plt)
    do
	echo $iplt 
	itime=$(echo $iplt | cut -d "." -f 1-2)
	ifig=$figures_dir$icase/$fig_prefix"_"$itime.jpg
	iplt=$simu_dir$icase"/tec_data/"$iplt

	solutiontime="  SOLUTIONTIME = "$itime
	sed -i "/$!GLOBALTIME/!b;n;c\ $solutiontime" $ilayout_dir

	mcr_layout="\$!OPENLAYOUT \"$ilayout_dir\""
	sed -i "/$!OPENLAYOUT/c\\$mcr_layout" \
	    $simu_dir$icase"/tecplot.mcr"

	##	mcr_data="ALTDATALOADINSTRUCTIONS = '\"$iplt\" \"$iplt\"'"
	mcr_data="ALTDATALOADINSTRUCTIONS = '\"$iplt\" \"$iplt\" \"$iplt\"'"	
	echo $mcr_data
	sed -i "/ALTDATALOADINSTRUCTIONS/c\\$mcr_data" \
	    $simu_dir$icase"/tecplot.mcr"

	mcr_fig="\$!EXPORTSETUP EXPORTFNAME = \"$ifig\""
	echo $mcr_fig
	sed -i "/EXPORTFNAME/c\\$mcr_fig" \
	    $simu_dir$icase"/tecplot.mcr"
	
	tec360 -b -p $simu_dir$icase"/tecplot.mcr"		
	echo "============================================"
    done
done     


